### ISSUE TITLE
ModelNotSupportedError: de_core_news_lg version 3.1.0

### ISSUE THREAD

**Issue by charobert** [msg-systems/coreferee#22]
Hi, I get this error message (using Spacy 3.1.3): 
>>> nlp=spacy.load('de_core_news_lg')
>>> nlp.add_pipe('coreferee')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Robert\anaconda3\lib\site-packages\spacy\language.py", line 776, in add_pipe
    pipe_component = self.create_pipe(
  File "C:\Users\Robert\anaconda3\lib\site-packages\spacy\language.py", line 660, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "C:\Users\Robert\anaconda3\lib\site-packages\thinc\config.py", line 729, in resolve
    resolved, _ = cls._make(
  File "C:\Users\Robert\anaconda3\lib\site-packages\thinc\config.py", line 778, in _make
    filled, _, resolved = cls._fill(
  File "C:\Users\Robert\anaconda3\lib\site-packages\thinc\config.py", line 850, in _fill
    getter_result = getter(*args, **kwargs)
  File "C:\Users\Robert\anaconda3\lib\site-packages\coreferee\manager.py", line 103, in __init__
    self.annotator = CorefereeManager().get_annotator(nlp)
  File "C:\Users\Robert\anaconda3\lib\site-packages\coreferee\manager.py", line 95, in get_annotator
    raise ModelNotSupportedError(''.join((nlp.meta['lang'], '_', nlp.meta['name'],
coreferee.errors.ModelNotSupportedError: de_core_news_lg version 3.1.0

Thank you!

**Comment by richardpaulhudson** [comment]
Hi @charobert, can you please confirm which versions of Python, Coreferee and the German Coreferee models you are using? For de_core_news_lg version 3.1.0 to work, you would need to be using the latest versions of both Coreferee and the German Coreferee models.
